version: "2"
services:
  apigility:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=192.168.102.32
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
